"""add_parent_job_id

Revision ID: 744409991e33
Revises: babd9266bd0f
Create Date: 2026-05-18 19:53:30.395356
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '744409991e33'
down_revision: Union[str, None] = 'babd9266bd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_research_jobs_parent_job_id'), 'research_jobs', ['parent_job_id'], unique=False)
    op.create_foreign_key(None, 'research_jobs', 'research_jobs', ['parent_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_research_jobs_parent_job_id'), table_name='research_jobs')
    op.drop_column('research_jobs', 'parent_job_id')
    # ### end Alembic commands ###
